### ISSUE TITLE
Update to latest version of Less?

### ISSUE THREAD

**Issue by jessegrosjean** [atom/less-cache#7]
I'd like to use some of the newer LESS features, but this cache is still based on LESS 1.7. Would it be possible to update that dependency?

**Comment by kevinsawicki** [comment]
It is definitely possible, we've upgraded in the past, it is just a matter of reviewing the upstream changes and testing things out.

**Comment by jessegrosjean** [comment]
I've created a pull request that updates to 2.4 and makes a few changes to make it all work. The less-cache specs are passing. Atom seems to work normally too, though I'm not sure if just launching Atom and switching themes tests this... that's what I did.

**Comment by thomasjo** [comment]
This was fixed in #10, so this issue can be closed.
